language: python
python:
  - 2.7
  - 3.4
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint pve_exporter
  - pyflakes pve_exporter
