---
os: linux
services: docker
language: python
python:
  - 3.6
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
env:
  global:
    - IMAGE_NAME: prompve/prometheus-pve-exporter
    - IMAGE_BUILD_ID: "travis-build-${TRAVIS_BUILD_ID}"
    - DOCKER_USERNAME: prompveci
    # travis encrypt DOCKER_PASSWORD=abcdefg[...]
    - secure: "UL0vSTw+8nKj1+a+5k2urlBdQCfrDYbWDWrEcIUN42c8m44OSKgUO2LLDlnJMVIrEdgOuY9pxaNjhkRRDSP8+RFDCwX2N355610qONcBAcUhZZbVXCU9aR29Lhnm1LZq13LDgs+05P9vQ9Aye2MSTKjsEPj1Rrx97GUNFUBfKbqhiV5e/++MLYHtcjsPSLjgBAfA80Tme/FwGbvBzL64OLUl1rmXnaUlAQ60FCag078RS8LlsMNZFEU11f1+DWxl9VdYdH83AzKN/t/xY2+qJu0eUksOvxFM19jMIrC9+KWzvSio3GpbPlA1R/eqpE8iWHx3Zo0tyeVllraYsxX4Wyn7XUqYVzw/5DmXA6gHYtgayrjDk6oA2qpsMmg9w+Q4fhQz7AJjLgNd/vXHwUBByzdgPfjT98zzUUwi2784o6e/+B7bZ3EeLSgrL0VuootmI4LTvlPjwFlWBKij9cQGSzSMiGomr7RcmZGPU9gFyA/EYkglxFV0sSMJgEOBi4Lostc8rEXThKF4eDcDQo7GdI4QvQ+0tQLzsbDAg17pm14+1b9WwqrwTCW1wCgR0T8VwH7wFvaiGnLbFuIWDT5KK4nSq9YOwYB+eLnO85N58ideqrM3o6FKnHqwscVzN4uIUMtCUgGgzS/gP+N7DMjN/OM2lkPIg4/fY45+5bEYhKI="
stages:
  - name: test
  - name: docker image
  - name: publish
    if: tag IS present
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - pylint pve_exporter
  - pyflakes src/pve_exporter
jobs:
  include:
    - stage: docker image
      install: skip
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - >
            docker build
            --tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
            --build-arg build_log_label="Travis CI Build #${TRAVIS_BUILD_NUMBER}"
            --build-arg build_log_url="${TRAVIS_BUILD_WEB_URL}"
            .
        - docker push "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
    - stage: publish
      install: skip
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - export VERSION_PATCH="${TRAVIS_TAG#v}"
        - export VERSION_MINOR="${VERSION_PATCH%.*}"
        - export VERSION_MAJOR="${VERSION_MINOR%.*}"
        - docker pull "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${VERSION_PATCH}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${VERSION_MINOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${VERSION_MAJOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:latest"
        - docker push "${IMAGE_NAME}:${VERSION_PATCH}"
        - docker push "${IMAGE_NAME}:${VERSION_MINOR}"
        - docker push "${IMAGE_NAME}:${VERSION_MAJOR}"
        - docker push "${IMAGE_NAME}:latest"
    - stage: publish
      install: skip
      script:
        - python3 setup.py sdist bdist_wheel --universal
      deploy:
        on:
          all_branches: true
        provider: pypi
        username: "__token__"
        password:
          secure: "iNCl+SFxXJEwDbg374UXLtIVJiXS6e8guAMP2sclIAZlJtzQ+LiydzCV2M4sS5BIyuNr82FsTOn+LGOds/qQiigWfsliM20mV3bgmOG6me6AyCUPJ/uF+lh6QwclrphuFwxyTJtxj4ttP+1vYJOGTaQTP0ElXoPXV48Ibhiz7R84SqTLnSWz3y8ZcRaqe/HYQ/8kNj/+ttwsBulDS4k+LD74PVuAjpw2VfFyRQuuHcRHDDgu81OYZsyfiGG24+VnOcARHs/04dMLHg/TJ54sJIjKp1VWHK7L20kZZTiuiTSIXaLEco3HtXVbeBLSDXjHEjj/PNxRqqcVtzjcnRcgZ6hq3g6hddttF9m3rnn4dmA0FCRgb/uqXqy6Ie2T4XPya7zY447s0b4f6E97DdKuc1xvuf3ESznwAdhjZ7wsUnDnS9MXaQf5SBwKQvWsBlsg/80aotC6FdLbP45HdrEskFza/IEdt2IpD1I5DSXVu2AOFbGig6BPkG1AXnlaNLE9SmNWTgHchUm+q1xD7txFEqee5j2in+AFDsQlB0qVXbbO5BDEUEucaLQ4hZMn7A3sVzaxEH9AMfIO3I3GF1nAaS1/B1eEzYelfxPiv/wzLJBPzJuXyyjgnkisv2W7sdyQsG2ZongvuDV3HHPlzKNU3+p4+h7NEMTCoyvnCpZIk6w="
