---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install -r requirements-test.txt

      - name: Install pve_exporter
        run: pip install .

      - name: Run pylint
        run: pylint pve_exporter

      - name: Run pyflakes
        run: pyflakes src/pve_exporter
